spring.application.name=api-gateway
server.port=8079

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true

# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

# IRCTC Booking Route
spring.cloud.gateway.server.webflux.routes[0].id=irctc-booking
spring.cloud.gateway.server.webflux.routes[0].uri=lb://IRCTC-BOOKING
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/irctc/booking/**

# Rate Limiter
spring.cloud.gateway.server.webflux.routes[0].filters[0].name=RequestRateLimiter
spring.cloud.gateway.server.webflux.routes[0].filters[0].args.redis-rate-limiter.replenishRate=5
spring.cloud.gateway.server.webflux.routes[0].filters[0].args.redis-rate-limiter.burstCapacity=5
spring.cloud.gateway.server.webflux.routes[0].filters[0].args.redis-rate-limiter.requestedTokens=1
spring.cloud.gateway.server.webflux.routes[0].filters[0].args.key-resolver=#{@ipKeyResolver}