spring.application.name=FlipkartProducts

server.port=8081

spring.data.mongodb.uri=mongodb+srv://ganeshsadhashivam_db_user:OMpcHabyIdk0203I@cluster0.cqlqpcp.mongodb.net/flipkart?retryWrites=true&w=majority

spring.data.redis.host=strong-fox-173512.upstash.io

spring.data.redis.port=6379
spring.data.redis.password=gQAAAAAAAqXIAAIgcDFjNzRjZTc1ODQxNGU0OWMxYmYxODgxYmYzZWNmYmE3MQ
spring.data.redis.ssl.enabled=true

spring.cache.type=redis

# OPTIONAL LOGS
logging.level.org.springframework.cache=TRACE
logging.level.org.springframework.data.redis=DEBUG